[package]
name = "vec_split"
version = "0.1.2"
edition = "2021"
description = "Splits arrays of vectors into arrays of items."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
